wandb:
  activate: False
  project: ""
  entity: ""

current_model:
  save_model: True
  model_dir: "models_h5"
  model_name: "TimmAdvancedModelSpectrogram"

reload_from_existing_model:
  activate: False
  model_dir: "models_h5"
  model_name: "TimmAdvancedModelSpectrogram"

model:
  TimmAdvancedModelSpectrogram:
    window_size: 256
    hop_size: 64
    ppm_lim: (0, 6)
    t_lim: (0, 0.3)
    timm_network: "vit_base_patch16_224"

epochs: 100

optimizer:
  Adam:
    lr: 0.0001

loss: MAELoss

lr_scheduler:
  activate: False
  scheduler_type: "cosineannealinglr"
  info:
    T_max: 10
    eta_min: 0.000001

train:
  batch_size: 35
  num_workers: 4

valid:
  batch_size: 200
  num_workers: 4

basis_set_path: data/basisset

train_dataset:
  DatasetSimpleFID:
    path_data: "data/train"

valid_dataset:
  DatasetSimpleFID:
    path_data: "data/valid"

valid_on_the_fly:
  activate: True
  save_dir_path: "valid_on_the_fly"

test_dataset:
  DatasetSimpleFID:
    path_data: "data/test"